name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  printname:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Print name
      run: echo "Hello. Using Java Version. My API_KEY is ${{secrets.API_KEY}}"
