name: Build Release App Bundle

on:   
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'keystore/your_signing_keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - uses: actions/checkout@v3

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: nathanmeade/ConnectionErrorJoke
          ref: githubActionCompatibility
          path: ConnectionErrorJoke

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Access API_KEY
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo API_KEY=\"$API_KEY\" > ./local.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: assemble release
        run: ./gradlew assembleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with: 
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}

      # - name: build prod
      #   run: ./gradlew assembleRelease
      #   env:
      #     SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      #     SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      #     SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: app/build/outputs/